### ISSUE TITLE
Make doesn't build the kernel, even after installing the dependencies. 

### ISSUE THREAD

**Issue by alexul1081** [lineageos-on-pdx201/android_kernel_sony_sm6125#2]
After trying for days and days continuously fixing the errors that it spits out every time. Of course, with ChatGPT, I don't have that kind of experience with Python. Especially with porting so many configs to current versions. Everything is out of date, requiring Python 2 and other stuff that is just no longer available today. I honestly have no idea what to do now to fix this error. I will paste it here.

```
CC      kernel/fork.o
In file included from kernel/fork.c:106:
./include/trace/events/sched.h:269:2: error: #error "Unsupported NR_CPUS for lb tracepoint."
  269 | #error "Unsupported NR_CPUS for lb tracepoint."
      |  ^~~~~
make[1]: *** [scripts/Makefile.build:362: kernel/fork.o] Error 1
make: *** [Makefile:1214: kernel] Error 2
```
This is not the only error I've encountered. There are many other errors that were fixed by only editing some code.
I think this issue is useless, because I really do not believe that anyone will read AND FIX this.
Ah, I was about to forget to mention the basic phone information. I have followed the guide to install LineageOS 20 on your repository, and have successfully managed to install it and the recovery. From the recovery, I've sideloaded Magisk, NikGapps and Kali NetHunter(only the app, this is the main reason for me wanting to build this kernel: to patch it with Kali Kernel Builder).

But the basic LineageOS 20 is working perfectly with no bugs. I am happy with my installation, but I would just like to report this issue and potentially fix it.

**Comment by alexul1081** [comment]
I just saw that there's a LineageOS 21 repository, so I will try installing that to my phone, then trying to build the newer kernel. I will keep you updated (whoever is "you").

**Comment by Mashopy** [comment]
You clearly have done something on your end since that error would trigger only if NR_CPUS would be superior to 32 which isn't the case for [pdx201_defconfig](https://github.com/lineageos-on-pdx201/android_kernel_sony_sm6125/blob/lineage-21/arch/arm64/configs/pdx201_defconfig#L76)
